site_name: FloydHub
site_url: https://www.floydhub.com
site_author: FloydHub Team
repo_url: https://github.com/floydhub/floyd-docs
pages:
    - Home: index.md
    - Get Started:
        - 'Quick Start': getstarted/quick_start.md
        - 'Jupyter Notebook': getstarted/quick_start_jupyter.md
    - Guides:
        - Basics:
            # - 'Core concepts': guides/basics/core_concepts.md
            - 'Install Floyd CLI': guides/basics/install.md
            - 'Login using Floyd CLI': guides/basics/login.md
            - 'Create new Project and Dataset': guides/basics/create_new.md
        - 'Mounting Data': guides/mounting_data.md
        - 'Environments': guides/environments.md
        - 'Ignore files': guides/floyd_ignore.md
        - 'Installing extra dependencies': guides/installing_dependencies.md
    - Examples:
        - 'Style Transfer': examples/style_transfer.md
    - FAQs:
        - 'Pricing FAQs': faqs/signup.md
        - 'Installation FAQs': faqs/installation.md
        - 'Signup and Login FAQs': faqs/authentication.md
        - 'Job FAQs': faqs/job.md
        - 'Environments FAQs': faqs/environments.md
        - 'Plans FAQs': faqs/plans.md
        - 'Billing FAQs': faqs/billing.md
    - Commands:
        - 'floyd': commands/index.md
        - 'floyd login': commands/login.md
        - 'floyd init': commands/init.md
        - 'floyd run': commands/run.md
        - 'floyd data': commands/data.md
        - 'floyd logs': commands/logs.md
        - 'floyd status': commands/status.md
        - 'floyd output': commands/output.md
        - 'floyd clone': commands/clone.md
        - 'floyd info': commands/info.md
        - 'floyd stop': commands/stop.md
        - 'floyd delete': commands/delete.md
        - 'floyd logout': commands/logout.md
        - 'floyd upgrade': commands/upgrade.md
        - 'floyd version': commands/version.md
    - Changelogs:
        - 'July 12 2017': changelogs/1.md
theme: material
extra:
  palette:
    primary: 'blue'
    accent: 'blue'
    extra:
  logo: 'img/f_white_small.png'
  font:
    text: 'Roboto'
    code: 'Source Code Pro'
  social:
    - type: 'github'
      link: 'https://github.com/floydhub'
    - type: 'twitter'
      link: 'https://twitter.com/floydhub_'
markdown_extensions:
    - markdown_include.include:
        base_path: docs
extra_css:
    - css/bootstrap_paper.min.css
    - css/style.css
copyright: Copyright &copy; 2017 Floyd Labs Inc.
