site_name: FloydHub Documentation
site_url: https://www.floydhub.com
site_author: FloydHub Team
repo_url: https://github.com/floydhub/floyd-docs
theme_dir: 'theme_overrides'
google_analytics: ['UA-90905407-1', 'floydhub.com']
pages:
    - Home: index.md
    - Get Started:
        - 'Core Concepts': getstarted/core_concepts.md
        - 'Quick Start': getstarted/quick_start.md
        - 'Quick Start - Jupyter Notebook': getstarted/quick_start_jupyter.md
        - 'Getting Started Tutorial': getstarted/get_started.md
        - 'Getting Started Tutorial - Jupyter Notebook': getstarted/get_started_jupyter.md
    - Projects:
        - 'Create a New Project': guides/basics/create_new.md
        - 'Delete a Project': guides/basics/delete.md
    - Jobs:
        - 'Run a Job': guides/run_a_job.md
        - 'Stop a Job': guides/stop_job.md
        - 'Restart a Job': guides/restart_job.md
        - 'Enable Tensorboard': guides/jobs/tensorboard.md
        - 'Delete a Job': guides/delete_job.md
        - 'Ignore Files': guides/floyd_ignore.md
        - 'SSH into a Job': guides/ssh.md
        - 'Troubleshooting & FAQs': faqs/job.md
    - Data:
        - 'Create and Upload a Dataset': guides/create_and_upload_dataset.md
        - 'Delete a Dataset': guides/delete_dataset.md
        - 'Mount Data to a Job': guides/data/mounting_data.md
        - 'Symlink Mounted Data': guides/data/symlink_mounted_data.md
    - Environments:
        - 'List of Available Environments': guides/environments.md
        - 'Install Extra Dependencies': guides/jobs/installing_dependencies.md
        - 'Using CPU vs GPU': guides/basics/using_gpu.md
        - 'Troubleshooting & FAQs': faqs/environments.md
        - 'SSH into a Job': guides/ssh.md
    - Output:
        - 'Save Output': guides/data/storing_output.md
        - 'Delete Output': guides/delete_output.md
        - 'Download Saved Output': guides/download_output.md
        - 'Browse Saved Output': guides/browse_output.md
        - 'Using Previous Output in a New Job': guides/reusing_output.md
    - Floyd CLI:
        - 'Install Floyd CLI': guides/basics/install.md
        - 'Log In Using Floyd CLI': guides/basics/login.md
        - CLI Commands:
          - 'floyd': commands/index.md
          - 'floyd login': commands/login.md
          - 'floyd init': commands/init.md
          - 'floyd run': commands/run.md
          - 'floyd data': commands/data.md
          - 'floyd logs': commands/logs.md
          - 'floyd status': commands/status.md
          - 'floyd output': commands/output.md
          - 'floyd clone': commands/clone.md
          - 'floyd info': commands/info.md
          - 'floyd stop': commands/stop.md
          - 'floyd delete': commands/delete.md
          - 'floyd logout': commands/logout.md
          - 'floyd upgrade': commands/upgrade.md
          - 'floyd version': commands/version.md
          - 'floyd restart': commands/restart.md
    - Examples:
        - 'Style Transfer': examples/style_transfer.md
        - 'Deep Text Corrector': examples/deep_corrector.md
        - 'Deep Convolutional Generative Adversarial Networks': examples/dcgan.md
    - Troubleshooting & FAQs:
        - 'Installation': faqs/installation.md
        - 'Signup and Login': faqs/authentication.md
        - 'Job': faqs/job.md
        - 'Plans': faqs/plans.md
        - 'Billing': faqs/billing.md
    # REDIRECTS:
    # To set up a redirect, add the file you want to redirect from in to the
    # list below, using this pattern:
    #
    # - "": home/using_datasets.md
    #
    # Any page with a "" title will not show up in the sidebar. This is a hack
    # we use to allow old URLs to exist while not showing them in the nav.
    #
    # Next, create a file in the location you specified and populate it with
    # the following, replacing <page> with the page you want to redirect to:
    #
    # <meta http-equiv="refresh" content="0;URL='<page>'"></meta>
    #
    # {!redirect_message.md!}
    #
    - "": home/using_datasets.md
    - "": home/install.md
    - "": home/getting_started.md
theme: material
extra:
  # Use this to make a section open by default in the sidebar. These names have
  # to match the titles in the `pages` section above. If a child section is
  # defaulted to open, but its parent is not, the parent will be closed, but
  # when you open the parent, the child will be open
  nav_items_open_by_default:
    - Projects
    - Jobs
    - Data
    - Environments
    - Output
    - Get Started
    - CLI Commands
  palette:
    primary: 'blue'
    accent: 'blue'
    extra:
  logo: 'img/f_white_rect_small.png'
  font:
    text: 'Roboto'
    code: 'Source Code Pro'
  social:
    - type: 'github'
      link: 'https://github.com/floydhub'
    - type: 'twitter'
      link: 'https://twitter.com/floydhub_'
markdown_extensions:
    - admonition
    - codehilite
    - footnotes
    - toc(permalink=true)
    - pymdownx.arithmatex
    - pymdownx.betterem(smart_enable=all)
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist(custom_checkbox=true)
    - pymdownx.tilde
    - markdown_include.include:
        base_path: docs
extra_css:
    - css/bootstrap_paper.min.css
    - css/style.css
copyright: Copyright &copy; 2017 FloydHub

# We were having some favicon issues, likely in our theme's code. This is a
# config setting offered by our theme that fixes the issue
# https://github.com/squidfunk/mkdocs-material/pull/319
site_favicon: 'img/favicon.ico'
